spring:
  application:
    name: desafio
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:usuarios
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: never
      encoding: UTF-8
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /doc.html
application:
  version: 0.0.1
  security:
    jwt:
      secret-key: SecretKeyParaJWTDesafioNeoris
      expiration: 10800000
